### ISSUE TITLE
Different Licenses: Readme vs. Silkscreen Board 

### ISSUE THREAD

**Issue by tinyledmatrix** [theacodes/Winterbloom-Big-Honking-Button#1]
Silkscreen on Bard (kicad and as far as I can See also on Twitter Image) indicates CC BY-SA 4.0. According to readme the License for the Hardware is CC BY-NC-SA 4.0. Is this difference on purpose?

**Comment by theacodes** [comment]
No, the readme is incorrect (it's from an older revision). I'll update it
shortly.

**Comment by theacodes** [comment]
Fixed!
