### ISSUE TITLE
property that is only triggered on falling edge

### ISSUE THREAD

**Issue by themoep** [theacodes/Winterbloom-Big-Honking-Button#5]
While trying to play a sound on button press and another on release, I made the mistake of using the `if bhb.released:` to trigger the second sound, resulting in a looping, glitchy sound while the button is not pressed.

As a workaround I added a is_pressed variable:
```
is pressed = False
while True:
    if bhb.triggered:
        is_pressed = True
        bhb.play(sample_p1, pitch_cv=bhb.pitch_in)

    if bhb.released and is_pressed:
        is_pressed = False
        bhb.play(sample_p2, pitch_cv=bhb.pitch_in)
```

It could be useful to add a stateful property that mimics this behavior of `triggered` and only is run once after the button has been released. Alternatively, this could be done in `released`.

**Comment by theacodes** [comment]
This is a great idea! I'll write up a patch for it soon. :)
