### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by machinehistories** [theacodes/Winterbloom-Big-Honking-Button#8]
I was wondering if the gate and button can be two separate functions. I was thinking of modifying the burst generator example by recording values coming in on the gate input jack. These lengths fill an array and I would also like to record the incoming cv values too. I know the length of recorded sampled values would be fairly short. Now when the button is pressed the arrays are both output on the respective jacks. Perhaps a long press button function could start and stop the record. If the gate input and button are separated then there could be double clicks and triple clicks and these could be used to change the overall functionality since you could load many examples and then change which is running on the fly with the button. Would this work.

**Comment by theacodes** [comment]
Hi @machinehistories,
Yes, the button and the gate in are connected to separate pins on the microcontroller, you can check the status of the button and gate in independently using `bhb.button` and `bhb.gate_in`. 

Let me know if you have any other questions, and feel free to pop by the [discord](https://winterbloom.com/contact) if you want - there's folks there (including me) that can help you.

(I'm closing this issue for now, but feel free to ask follow-up questions)
